---

language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
matrix:
  allow_failures:
    - python: "2.7"
install:
  - pip install docutils tox tox-travis
script:
  - tox -v
